# Generated by Django 4.2.1 on 2023-06-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=1000)),
                ('userid', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('passwordcheck', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='address_dong',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='address_road',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='store_code',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='store_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='store_segment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinputmodel',
            name='store_area',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinputmodel',
            name='store_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinputmodel',
            name='store_select',
            field=models.CharField(max_length=1000),
        ),
    ]
